### ISSUE TITLE
Quotes with images

### ISSUE THREAD

**Issue by FroggMaster** [FroggMaster/spooks-chatjs#10]
If you have to scroll up to view a quote that contains an image you will be instantly sent to the bottom of the chat without being able to view the quote.

**Comment by ghost** [comment]
Appears to be a general problem. I use iceweasel (firefox) and it scrolls down when a new message appears or I start typing in the box.

**Comment by FroggMaster** [comment]
I've noticed on Chrome; When you start typing it jumps to the bottoms as well.
This feature I do not mind as having it jump to the bottom when you're typing is nice.

I can't seem to replicate the issue of it auto-scrolling upon new messages in FF or Chrome; That might have to do with the IceWeasel build.

Aside from that; It seems quotes with images force you to the bottom of the chat with FF or Chrome as well.

**Comment by ghost** [comment]
~~I think I know why, it's because a new message appears in the middle of scrolling up. I think I can fix the problem...
It's not a bad thing, means the chat is busy.~~
OK i see I talked to sammich and he clarified for me.
