### ISSUE TITLE
2Spooks move to other file

### ISSUE THREAD

**Issue by ghost** [FroggMaster/spooks-chatjs#110]
2spooks needs to be moved to a seperate file for readability and minimalising
server.js or some shit

**Comment by FroggMaster** [comment]
This would be nice.

**Comment by correcthorsebatterystaple-sudo** [comment]
2spooks is honestly a buggy pile of trash. It needs to be rewritten by Mr.Guy and Bruno.

**Comment by FroggMaster** [comment]
2Spooks needs to be removed from Server.js It's been causing major crashes lately. Line 1779
It needs to be put in it's own file like Doom's has suggested.

**Comment by Bruno02468** [comment]
Frogger: how will moving it to another file prevent crashes?
Doesn't matter where the broken code is... if it's broken, it's going to cause trouble, period.

And dooms' suggestion was a little unspecific as to how much of the bot's code should be moved somewhere else, I mean, are we talking just the functions to another file to shrink server.js?

**Comment by FroggMaster** [comment]
Yea just move it to another file to be specific; Should clean up/shrink the server.js and it will hopefully increase stability too.

Right now what's happening is Server.js is crashing; Leaving all the other scripts running.
If it's simply the 2Spooks file that crashes I can better pinpoint the error, not to mention the main file should continue to run like the other scripts do, meaning only 2Spooks code will crash and stop functioning. (In theory, the Server.js should continue to run and the 2Spooks code will wait until it can be properly restarted.)

**Comment by Bruno02468** [comment]
That's not as simple as you may be thinking, that would require 2Spooks to "run" on another thread or something like that (unlikely).
Maybe there could be a "master shutdown" 2Spooks command that basically "un-defines" all the 2Spooks functions, making the bot do absolutely nothing.
Or it could maybe just get rid of the handlers in the COMMANDS... Whatever you do, putting it in another file WILL make it easier to pinpoint the source of the error, it WILL make the server.js cleaner, but WILL NOT improve stability unless you combine it with some method to shut the bot down altogether.

**Comment by FroggMaster** [comment]
For now just move it to a spooksbot.js file; It's going to make things easier and cleaner in the long run to work with.

**Comment by Bruno02468** [comment]
> mfw I don't know how to #include files in node.js programs

**Comment by ghost** [comment]
What's wrong with having 2spooks connect through it's own node.js process?

**Comment by FroggMaster** [comment]
Final decision is to refactor code so it is not a pile of shit.
