### ISSUE TITLE
Spoof IP

### ISSUE THREAD

**Issue by FroggMaster** [FroggMaster/spooks-chatjs#125]
Xultra's a fag.

**Comment by correcthorsebatterystaple-sudo** [comment]
To elaborate to a further extent than "I love penis.": 
The current system of IP authentication uses the X-FORWARDED-FOR from the User Agent as the means of getting the IP for the SQL. This means, from the client side, anyone can edit their own IP and use any string. Personally, I like to use FroggerMaster's IP as mine. :^)
