### ISSUE TITLE
/lock multiple issues

### ISSUE THREAD

**Issue by FroggMaster** [FroggMaster/spooks-chatjs#17]
/lock only accepts the first digit and ignores the second digit if one is presented.
Eg.

> /lock admin 10 = /lock admin 1

If a command is locked to Admin 0, Super or God it can  still be unlocked by an Admin 1+

**Comment by ghost** [comment]
works for me...
reopen if it happens again.

**Comment by FroggMaster** [comment]
I did some further testing. (Ignore "That is already topic, I had set the same topic far to many times.)
Everything else is relevant.

If command is locked to God or Super
Admin 0 + can still use the command as if it's not locked
Admin 0 + can /lock command admin 0

If command is locked to Admin 0
Admin 1 + cannot use the command
Admin 1 + can /lock command admin 1

![ty3h7jt 1](https://cloud.githubusercontent.com/assets/12762784/8249640/4a85b0d4-1621-11e5-94f5-8a638ac8a4ef.png)

**Comment by FroggMaster** [comment]
Changed access to this command to Supers and Gods.

**Comment by FroggMaster** [comment]
I've removed all access to the LOCK command from Admins. They do not need access to this command, 
Supers can still unlock a command left locked by the God.
