### ISSUE TITLE
Anonymous Nicks

### ISSUE THREAD

**Issue by FroggMaster** [FroggMaster/spooks-chatjs#48]
Anonymous nicks need to be changed; They're just down right bloody confusing, the only person they're helping is trolls and spammers.

If we can implement an array of keywords again like we use to previously have; That would be wonderful. User IDs should continue to exist. (Hopefully this will also solve the lingering anon issue: https://github.com/FroggMaster/spooks-chatjs/issues/31)

**Comment by ghost** [comment]
Main problem fixed. Other parts of Anonymous will be removed soon.
