### ISSUE TITLE
Unable to kick Anonymous users

### ISSUE THREAD

**Issue by FroggMaster** [FroggMaster/spooks-chatjs#5]
Anonymous users cannot be kicked.

**Comment by ghost** [comment]
fixed, not sure why it didn't close automatically

**Comment by ghost** [comment]
Oh, and I should say how it works:

You have to either wait for them to talk (so they say their full ID)
e.g.: Anonymous(bunch of stuff): i'm spamming

OR

Use the menu and click their name. Should be a bit hard if they've been here for a while, but I will fix the IP thing later so it's easier.
