### ISSUE TITLE
Auto Scroll

### ISSUE THREAD

**Issue by FroggMaster** [FroggMaster/spooks-chatjs#56]
<s>Not sure why this has started; Whenever someone sends a new message the chat is instantly scrolled to the bottom.

<s>Definitely don't like this feature; If this is something you'd like added; 
Please make it toggleable and disabled by default.

Otherwise, just remove all together.</s>

UPDATE:

-A quote with an image will send you to the bottom of the chat if you have to scroll to read it.

-When someone sends an image, it will scroll the chat automatically to the bottom.

-When you click on the input box and type it will send you to the bottom of the chat.

-The only time the chat should auto scroll to the bottom is if the user is already at the bottom of the chat.

<s>-If we can also add a /bottom command to scroll to the bottom of the chat and /top to go to the top.</s>
Home / End on the keyboard works just fine.

**Comment by ghost** [comment]
~~Not one of mine and will be removed soon.~~
You mean messages or when you start typing in the input box?

**Comment by FroggMaster** [comment]
You're correct; It's the input box.
As soon as you type anything; Or press tab it'll shoot directly to the bottom of the chat.

I've updated the main issue with further information.

**Comment by FroggMaster** [comment]
It will also auto scroll if an image is posted.

**Comment by FroggMaster** [comment]
-A quote with an image will send you to the bottom of the chat if you have to scroll to read it.

-When someone sends an image, it will scroll the chat automatically to the bottom.

-When you click on the input box and type it will send you to the bottom of the chat.

-The only time the chat should auto scroll to the bottom is if the user is already at the bottom of the chat.

-If we can also add a /bottom command to scroll to the bottom of the chat and /top to go to the top.

**Comment by correcthorsebatterystaple-sudo** [comment]
Done, bruh.

**Comment by ghost** [comment]
you did good job very proud of you
love, doomsies

**Comment by ghost** [comment]
now legit fixed
