### ISSUE TITLE
RPS

### ISSUE THREAD

**Issue by FroggMaster** [FroggMaster/spooks-chatjs#77]
-If you're challenged by Challenger1, then directly after before choosing an option challenged by Challenger2. The game with Challenger1 becomes Challenger2

http://i.imgur.com/SolIy5j.png

-If you type /rps <name> <anything> you will still be able to challenge/play even though you're not choosing a valid option.

-Some sort of delay to prevent RPS spam would be #swag

**Comment by Bruno02468** [comment]
On it.

**Comment by LandonPowell** [comment]
lmao

**Comment by correcthorsebatterystaple-sudo** [comment]
Bruno, you goof. <3

**Comment by correcthorsebatterystaple-sudo** [comment]
To add to the bugs; I can also just ignore messages and not have to see the 'pussied out' message.

**Comment by Bruno02468** [comment]
well, that means you pussied out anyway.

**Comment by FroggMaster** [comment]
#Rekt

**Comment by Bruno02468** [comment]
my pull request ficks it all, pls close

**Comment by Bruno02468** [comment]
CLOSE THIS. GOD DAMN.
