### ISSUE TITLE
/r 

### ISSUE THREAD

**Issue by FroggMaster** [FroggMaster/spooks-chatjs#8]
If someone PM's you and then another person PMs you /r will go to the first person who has PMed you.

Rather then the most recent. >Causing PM's to be sent to incorrect people.

**Comment by ghost** [comment]
Oh it's automatic

**Comment by FroggMaster** [comment]
Not sure if the GIT has been pulled to SSH but:
http://i.imgur.com/2tOdVtm.png

**Comment by ghost** [comment]
No, It hasn't been. You'll have to pull to make it work.
