### ISSUE TITLE
/get command broken

### ISSUE THREAD

**Issue by ghost** [FroggMaster/spooks-chatjs#81]
/get only returns if attribute is toggled or not
e.g. /get flair returns "flair is currently set to: on"
CLIENT.get('attribute') still works

**Comment by correcthorsebatterystaple-sudo** [comment]
It's like issues with spooks appear out of nowhere. How the hell does everything keep breaking?

**Comment by ghost** [comment]
Because we're maintaining legacy code that was poorly written initially

**Comment by FroggMaster** [comment]
fixd
