### ISSUE TITLE
Ban issue

### ISSUE THREAD

**Issue by FroggMaster** [FroggMaster/spooks-chatjs#84]
I'm not going to go in depth on how to replicate the issue until we've resolved it

/ban
/banip

Only an issue for Admins 1, 2 and 3
These commands are suppose to only function for Admins 0+

Basics can't  to take advantage of this.
Mods also cannot take advantage of this.

Both of these need to be resolved.
Most of us already know the issue here; I don't think anyone needs an overview but if you do ask me.

**Comment by ghost** [comment]
You're welcome<3

**Comment by FroggMaster** [comment]
Fixed

**Comment by ghost** [comment]
still works

**Comment by FroggMaster** [comment]
I haven't updated the production server. I tested it though as an Admin 1.

Edit:
Production server is up to date now.
